version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sd_sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SdStrongPass!2025
    ports:
      - "14333:1433"
    volumes:
      - sd_sql_data:/var/opt/mssql
    networks:
      - sd_net

  api:
    build:
      context: .
    #  dockerfile: FISEI.ServiceDesk.Api/Dockerfile  # si ya lo tienes así, déjalo
      dockerfile: FISEI.ServiceDesk.Api/Dockerfile
    container_name: sd_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ServiceDeskDB;User ID=sa;Password=SdStrongPass!2025;TrustServerCertificate=True;
      - BlazorOrigin=http://localhost:8090
    depends_on:
      - sqlserver
    ports:
      - "8070:8080"
    networks:
      - sd_net

  web:
    build:
      context: .
      dockerfile: FISEI.ServiceDesk.Web/Dockerfile
    container_name: sd_web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiBaseUrl=http://api:8080
    depends_on:
      - api
    ports:
      - "8090:8090"
    networks:
      - sd_net

networks:
  sd_net:

volumes:
  sd_sql_data: